#!/bin/bash

#/usr/bin/parallel-ssh -i -h backwall -x "-T -o StrictHostKeyChecking=no" -A pwomxplayer -A udp://239.0.1.23:1234?buffer_size=1200000B
#exit

#avconv -re -i movie.avi -vcodec copy -f avi -an udp://239.0.1.23:1234
#avconv -re -i "$1" -vcodec copy -f h264 -an udp://239.0.1.23:1234
while true; do
  toilet -f big -t -F border "[[   N 0  B 4 D  M 3 M 0 R 1 3 5   ]]"
  toilet -f big -t -F border "[[   N 0  B 4 D  M 3 M 0 R 1 3 5   ]]"
  avconv -re -flags loop -i "$1" -vcodec copy -f avi -an udp://239.0.1.23:1234
  #sleep 28s
  toilet -f big -t -F border "[[   N 0  B 4 D  M 3 M 0 R 1 3 5   ]]"
done

